sudo: required
services:
  - docker

before_install:
  - docker build -t suu222o2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sue222o2/react-test npm test

after_success:
  - docker build -t sue222o2/multi-client ./client
  - docker build -t sue222o2/multi-nginx ./nginx
  - docker build -t sue222o2/multi-server ./server
  - docker build -t sue222o2/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sue222o2/multi-client
  - docker push sue222o2/multi-nginx
  - docker push sue222o2/multi-worker
  - docker push sue222o2/multi-server
